from django.db import models
from django.utils import timezone

class BaseModel(models.Model):
    user_id = models.IntegerField()
    table = models.CharField(max_length=50)
    guid = models.CharField(max_length=50)
    platform = models.IntegerField()
    _modified = models.DateTimeField(default=timezone.now)

    class Meta:
        abstract = True

class Aircraft(BaseModel):
    fin = models.CharField(max_length=255, blank=True, null=True)  
    sea = models.BooleanField(default=False)  
    tmg = models.BooleanField(default=False)
    efis = models.BooleanField(default=False)
    fnpt = models.IntegerField(blank=True, null=True)
    make = models.CharField(max_length=255, blank=True, null=True)
    run2 = models.BooleanField(default=False)
    Class = models.IntegerField(blank=True, null=True)
    model = models.CharField(max_length=255, blank=True, null=True)
    power = models.IntegerField(blank=True, null=True)
    seats = models.IntegerField(blank=True, null=True)
    active = models.BooleanField(default=True)
    kg5700 = models.BooleanField(default=False)  
    rating = models.CharField(max_length=255, blank=True, null=True)
    company = models.CharField(max_length=255, blank=True, null=True)
    complex = models.BooleanField(default=False)  
    condlog = models.IntegerField(blank=True, null=True)  
    favlist = models.BooleanField(default=False)  
    category = models.IntegerField(blank=True, null=True)  
    highperf = models.BooleanField(default=False)
    submodel = models.CharField(max_length=255, blank=True, null=True)  
    aerobatic = models.BooleanField(default=False)  
    refsearch = models.CharField(max_length=255, blank=True, null=True)  
    reference = models.CharField(max_length=255, blank=True, null=True)  
    tailwheel = models.BooleanField(default=False)  
    defaultapp = models.IntegerField(blank=True, null=True)  
    defaultlog = models.IntegerField(blank=True, null=True)  
    defaultops = models.IntegerField(blank=True, null=True)  
    devicecode = models.IntegerField(blank=True, null=True)  
    aircraftcode = models.CharField(max_length=50, blank=True, null=True)
    defaultlaunch = models.IntegerField(blank=True, null=True)  
    record_modified = models.DateTimeField(default=timezone.now)

class Airfield(BaseModel):
    afcat = models.IntegerField()  
    afcode = models.CharField(max_length=255)
    afiata = models.CharField(max_length=10, null=True, blank=True)
    aficao = models.CharField(max_length=10)
    afname = models.CharField(max_length=255)  
    tzcode = models.IntegerField()
    latitude = models.IntegerField()
    showlist = models.BooleanField()  
    afcountry = models.IntegerField()
    longitude = models.IntegerField()
    notesuser = models.CharField(max_length=255, blank=True, null=True)
    regionuser = models.IntegerField()
    elevationft = models.IntegerField()
    record_modified = models.DateTimeField(default=timezone.now)
    
class SettingConfig(BaseModel):
    data = models.CharField(max_length=255, blank=True, null=True)
    name = models.CharField(max_length=255)
    group = models.CharField(max_length=255)
    configcode = models.IntegerField()
    record_modified = models.DateTimeField(default=timezone.now)
    
class ImagePic(BaseModel):
    fileext = models.CharField(max_length=10, blank=True, null=True)
    imgcode = models.UUIDField()  
    filename = models.CharField(max_length=255)  
    linkcode = models.UUIDField()
    img_upload = models.BooleanField()  
    img_download = models.BooleanField()  
    record_modified = models.DateTimeField(default=timezone.now)


class Pilot(BaseModel):
    notes = models.TextField(blank=True, null=True)
    active = models.BooleanField(default=True)
    company = models.CharField(max_length=255, blank=True, null=True)
    favlist = models.BooleanField(default=True)
    userapi = models.CharField(max_length=255, blank=True, null=True)
    facebook = models.CharField(max_length=255, blank=True, null=True)
    linkedin = models.CharField(max_length=255, blank=True, null=True)
    pilotref = models.CharField(max_length=255, blank=True, null=True)  
    pilotcode = models.UUIDField() 
    pilotname = models.CharField(max_length=255, null=True)
    pilotemail = models.EmailField(blank=True, null=True)
    pilotphone = models.CharField(max_length=20, blank=True, null=True)
    certificate = models.CharField(max_length=255, blank=True, null=True)
    phonesearch = models.CharField(max_length=255, blank=True, null=True)
    pilotsearch = models.CharField(max_length=255, null=True)
    rosteralias = models.CharField(max_length=255, blank=True, null=True)
    record_modified = models.DateTimeField(default=timezone.now)

class MyQueryBuild(BaseModel):
    build1 = models.CharField(max_length=255, blank=True, null=True)
    build2 = models.IntegerField(blank=True, null=True)
    build3 = models.IntegerField(blank=True, null=True)
    build4 = models.CharField(max_length=255, blank=True, null=True)
    mqcode = models.UUIDField()
    mqbcode = models.UUIDField()
    record_modified = models.DateTimeField(default=timezone.now)

class MyQuery(BaseModel):
    name = models.CharField(max_length=255)
    mqcode = models.UUIDField()
    quickview = models.BooleanField(default=False)
    shortname = models.CharField(max_length=255, blank=True, null=True)
    record_modified = models.DateTimeField(default=timezone.now)


class LimitRules(BaseModel):
    lto = models.DateField()  
    lfrom = models.DateField()  
    ltype = models.IntegerField()  
    lzone = models.IntegerField()
    lminutes = models.IntegerField()
    limitcode = models.UUIDField()
    lperiodcode = models.IntegerField()
    record_modified = models.DateTimeField(default=timezone.now)


class Qualification(BaseModel):
    qcode = models.UUIDField()
    refextra = models.IntegerField(blank=True, null=True)  
    refmodel = models.CharField(max_length=255, blank=True, null=True)
    validity = models.IntegerField(blank=True, null=True)
    datevalid = models.DateField(blank=True, null=True)
    qtypecode = models.IntegerField(blank=True, null=True)
    dateissued = models.DateField(blank=True, null=True)
    minimumqty = models.IntegerField(blank=True, null=True)
    notifydays = models.IntegerField(blank=True, null=True)
    refairfield = models.UUIDField()
    minimumperiod = models.IntegerField(blank=True, null=True)
    notifycomment = models.TextField(blank=True, null=True)
    record_modified = models.DateTimeField(default=timezone.now)



class Flight(BaseModel):
    pf = models.BooleanField(default=False)
    pax = models.IntegerField(blank=True, null=True)
    fuel = models.IntegerField(blank=True, null=True)
    deice = models.BooleanField(default=False)
    route = models.CharField(max_length=255, blank=True, null=True)
    today = models.IntegerField(blank=True, null=True)
    minu1 = models.IntegerField(blank=True, null=True)
    minu2 = models.IntegerField(blank=True, null=True)
    minu3 = models.IntegerField(blank=True, null=True)
    minu4 = models.IntegerField(blank=True, null=True)
    minxc = models.IntegerField(blank=True, null=True)
    arrrwy = models.CharField(max_length=255, blank=True, null=True)
    deprwy = models.CharField(max_length=255, blank=True, null=True)
    ldgday = models.IntegerField(blank=True, null=True)  
    liftsw = models.IntegerField(blank=True, null=True)
    p1code = models.UUIDField()
    p2code = models.UUIDField()
    p3code = models.UUIDField()
    p4code = models.UUIDField()
    report = models.CharField(max_length=255, blank=True, null=True)
    tagops = models.CharField(max_length=255, blank=True, null=True)  
    toedit = models.BooleanField(default=False)
    minair = models.IntegerField(blank=True, null=True)
    mincop = models.IntegerField(blank=True, null=True)
    minifr = models.IntegerField(blank=True, null=True)
    minimt = models.IntegerField(blank=True, null=True)
    minpic = models.IntegerField(blank=True, null=True)  
    minrel = models.IntegerField(blank=True, null=True)
    minsfr = models.IntegerField(blank=True, null=True)
    arrcode = models.UUIDField()
    dateutc = models.DateField(default=timezone.now)  
    depcode = models.UUIDField()
    hobbsin = models.IntegerField(blank=True, null=True)
    holding = models.IntegerField(blank=True, null=True)
    pairing = models.CharField(max_length=255, blank=True, null=True)
    remarks = models.CharField(max_length=255, blank=True, null=True)
    signbox = models.IntegerField(blank=True, null=True)  
    tonight = models.IntegerField(blank=True, null=True)
    mindual = models.IntegerField(blank=True, null=True)
    minexam = models.IntegerField(blank=True, null=True)
    crewlist = models.CharField(max_length=255, blank=True, null=True) 
    datebase = models.DateField(default=timezone.now)
    fuelused = models.IntegerField(blank=True, null=True)
    hobbsout = models.IntegerField(blank=True, null=True)
    ldgnight = models.IntegerField(blank=True, null=True)
    nextpage = models.BooleanField(default=False)
    tagdelay = models.CharField(max_length=255, blank=True, null=True)
    training = models.CharField(max_length=255, blank=True, null=True)
    userbool = models.BooleanField(default=False)
    usertext = models.CharField(max_length=255, blank=True, null=True)
    mininstr = models.IntegerField(blank=True, null=True)
    minnight = models.IntegerField(blank=True, null=True)
    minpicus = models.IntegerField(blank=True, null=True)
    mintotal = models.IntegerField(blank=True, null=True)
    arroffset = models.IntegerField(blank=True, null=True)  
    datelocal = models.DateField(default=timezone.now)  
    depoffset = models.IntegerField(blank=True, null=True)
    taglaunch = models.CharField(max_length=255, blank=True, null=True)
    taglesson = models.CharField(max_length=255, blank=True, null=True)  
    totimeutc = models.IntegerField(blank=True, null=True)
    arrtimeutc = models.IntegerField(blank=True, null=True)  
    baseoffset = models.IntegerField(blank=True, null=True)
    deptimeutc = models.IntegerField(blank=True, null=True)  
    flightcode = models.UUIDField()  
    ldgtimeutc = models.IntegerField(blank=True, null=True)
    fuelplanned = models.IntegerField(blank=True, null=True)
    nextsummary = models.BooleanField(default=False)
    tagapproach = models.CharField(max_length=255, blank=True, null=True)
    aircraftcode = models.UUIDField()
    arrtimesched = models.IntegerField(blank=True, null=True)
    deptimesched = models.IntegerField(blank=True, null=True)  
    flightnumber = models.CharField(max_length=255, blank=True, null=True)
    flightsearch = models.CharField(max_length=255, blank=True, null=True)
    record_modified = models.DateTimeField(default=timezone.now)



